### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anurag-bit** [excalith/dev-cheats#15]
**Describe the bug**
the Production Deployment instance isn't working, entering into the search bar doesn't perform anything at all, even after keyboard 😭input! 

**To Reproduce**
1. Go to 'Production Deployment'
2. Click on 'try searching'

**Comment by excalith** [comment]
Hello @anurag-bit, please complete the whole issue template including the title. For instance, I am unable to reproduce this on my end. Please add browser and OS versions, console logs and screenshots.

**Comment by anurag-bit** [comment]
I've re-tested, and issue is fixed , great job!!
