### ISSUE TITLE
[DOCS] Request: java

### ISSUE THREAD

**Issue by swapnilxi** [excalith/dev-cheats#27]
**Official Repo or Website Link**
Please provide official link to the website or repository

**Existing official documentation**
If exists, please provide the official documentation link

**Additional Context**
Please provide any additional context or information that may be useful for the documentation

**Comment by excalith** [comment]
Hello @swapnilxi, please fill the template before opening an issue. It basically says what you should fill. 

And also, Java is a programming language which is out of this projects scope. Dev Cheats aims to give developers cheatsheets for command line based tools. If you meant a spesific thing related to Java, please add it to additional context field of the issue template as well.

Cheers!
